Refactor Github actions

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -5,16 +5,29 @@ on:
     paths:
       - '**/*.cpp'
       - '**/*.h'
+      - '**.ts'
+      - '**.ui'
+      - '.github/workflows/*.yaml'
   push:
     branches:
       - main
 
 jobs:
+  actions-lint:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Check workflow files
+        run: |
+          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
+          ./actionlint -color
+        shell: bash
+
   clang-format-lint:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4
 
       - name: Install clang-format
         run: sudo apt-get install -y clang-format
@@ -22,4 +35,33 @@ jobs:
       - name: Check formatting
         run: |
           FILES=$(find . -regex '.*\.\(cpp\|h\)')
-          clang-format --dry-run --Werror -style=file $FILES
+          clang-format --dry-run --Werror -style=file "$FILES"
+
+  check-translations:
+    runs-on: ubuntu-latest
+
+    env:
+      QT_VERSION: 6.9.1
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Set up Qt
+        uses: jurplel/install-qt-action@v3
+        with:
+          version: ${{ env.QT_VERSION }}
+
+      - name: Generate .ts files with lupdate
+        run: |
+          lupdate src/ -ts locale/*.ts
+
+      - name: Check for unfinished translations
+        run: |
+          if grep -q 'type="unfinished"' locale/fr_FR.ts; then
+            echo "::error ::Unfinished locale found:"
+            grep -Hn 'type="unfinished"' locale/fr_FR.ts
+            exit 1
+          else
+            echo "✅ All translations are complete."
+          fi
